#!/usr/bin/env python3
"""Einmaliger Cutover der Issue-Triage aus ``RECOMMENDATIONS.md`` nach GitHub (#1033).

Bis #1033 stand die Triage des offenen Bestands (Relevanz, Komplexität,
nächster Schritt) in einer sechsfach gespiegelten Tabelle. Dieses Skript
überträgt sie **einmalig** in die Issues selbst: Jedes offene Issue trägt
genau ein ``prio:*``-Label, interne Blocker werden als native
GitHub-Abhängigkeit („blocked by") gesetzt, externe Blocker als
``blocked:extern`` plus Kommentarzeile, und jede Tabellenzeile des
Legacy-Bestands landet wortgleich als Übernahmekommentar im Issue. Die
Spalte „Empfohlenes Modell“ wird bewusst **nicht** übernommen.

Warum ein Skript und kein Handlauf: 52 Issues, 41 Kommentare und rund 60
Abhängigkeiten sind von Hand fehleranfällig, und die beiden
Abnahme-Abgleiche des Issues (Tabellenzeilen ↔ Übernahmekommentare, offener
Live-Bestand ↔ genau ein ``prio:*``-Label) sollen reproduzierbar aus
derselben Quelle kommen wie die Änderung selbst. Die ``prio:*``-Zuordnung
ist laut Issue eine **einmalige Priorisierungsentscheidung des Owners**;
sie steht hier als versionierte Akte (``DECISIONS``), mit der Regel je
Zeile, damit der Kommentar sie nennen kann.

Das ist ausdrücklich **kein dauerhafter Wächter** (Nicht-Ziel in #1033):
kein Test liest den Live-Bestand, kein Workflow ruft das Skript. ``apply``
ist idempotent (vorhandene Labels, Abhängigkeiten und Kommentare werden
erkannt und übersprungen), ``verify`` bewertet nur und schreibt nichts.
Nach #1040 (Entfernung der Tabelle) hat das Skript seinen Zweck erfüllt.

Aufrufe (Token aus ``GH_TOKEN``/``GITHUB_TOKEN``; ohne Token laufen die
Anfragen anonym – hinter einem authentifizierenden Proxy genügt das)::

    python scripts/triage_issue_cutover.py plan
    python scripts/triage_issue_cutover.py apply --dry-run
    python scripts/triage_issue_cutover.py apply
    python scripts/triage_issue_cutover.py verify
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Final

REPO: Final = "NikolayDA/picture_helper"
API_ROOT: Final = "https://api.github.com"
USER_AGENT: Final = "bgremover-triage-issue-cutover"
REQUEST_TIMEOUT_S: Final = 60.0

#: Stand der übertragenen Tabelle (41 Legacy-Zeilen). Die Zeilen sind
#: zwischen diesem Commit und dem Cutover-Stand textgleich (geprüft per
#: ``git diff dd6c572 HEAD -- RECOMMENDATIONS.md``); der Cutover-Commit
#: steht zusätzlich im Abschlusskommentar.
TABLE_COMMIT: Final = "dd6c572"
TABLE_DATE: Final = "2026-09-07"

PRIO_NOW: Final = "prio:now"
PRIO_NEXT: Final = "prio:next"
PRIO_LATER: Final = "prio:later"
PRIO_LABELS: Final = (PRIO_NOW, PRIO_NEXT, PRIO_LATER)
BLOCKED_EXTERN: Final = "blocked:extern"

#: Labelvertrag (Name, Farbe, Beschreibung). Bewusst kein ``status:ready``
#: und kein Label für interne Blocker – das wären Zustände, die GitHub selbst
#: kennt und die von Hand synchron gehalten werden müssten (Anti-Loop-Regel).
LABEL_SPECS: Final[tuple[tuple[str, str, str], ...]] = (
    (PRIO_NOW, "b60205", "Als Nächstes empfohlen – zuerst bearbeiten"),
    (PRIO_NEXT, "d93f0b", "Danach – eingeplant, aber nicht das nächste Paket"),
    (PRIO_LATER, "fbca04", "Zurückgestellt oder mehrstufig blockiert"),
    (
        BLOCKED_EXTERN,
        "5319e7",
        "Blockiert durch etwas, das kein Issue ist (Hardware, Account, Billing, Release-Lauf)",
    ),
)

COMMENT_MARKER: Final = "**Triage-Übernahme aus RECOMMENDATIONS.md"
EXTERN_PREFIX: Final = "Blockiert extern durch: "
EPIC_ISSUE: Final = 1032
EPIC_MARKER: Final = "**Übernahme „Als Nächstes empfohlen“ aus RECOMMENDATIONS.md"
FOOTER: Final = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"

TRIAGE_SECTION_RE: Final = re.compile(r"(?ms)^## Offene GitHub-Issues.*?(?=^## |\Z)")
NEXT_STEPS_RE: Final = re.compile(r"(?ms)^### Als Nächstes empfohlen\s*\n(.*?)(?=^##|\Z)")
ISSUE_LINK_RE: Final = re.compile(r"^\[#(\d+)]\(https://github\.com/[^)]+/issues/(\d+)\)$")
NEXT_ITEM_RE: Final = re.compile(r"^(\d+)\.\s+(.*)$")


class CutoverError(RuntimeError):
    """Inkonsistenz zwischen Tabelle, Entscheidungsakte und Live-Bestand."""


@dataclass(frozen=True)
class TriageRow:
    """Eine Zeile der Triage-Tabelle (ohne die nicht übernommene Modellspalte)."""

    number: int
    title: str
    relevance: str
    complexity: str
    next_step: str


@dataclass(frozen=True)
class Decision:
    """Einmalige Owner-Entscheidung je offenem Issue.

    ``blocked_by`` sind interne Blocker (native Abhängigkeit, kein Label);
    ``extern`` ist der Grund eines externen Blockers (Label + Kommentarzeile);
    ``note`` markiert eine bewusste Abweichung vom Tabellentext.
    """

    prio: str
    rule: str
    blocked_by: tuple[int, ...] = ()
    extern: str | None = None
    note: str | None = None


@dataclass(frozen=True)
class LiveIssue:
    number: int
    issue_id: int
    labels: frozenset[str]


@dataclass(frozen=True)
class Action:
    kind: str
    issue: int
    payload: str = ""


@dataclass
class VerifyReport:
    checked_at: str
    query: str
    open_count: int
    problems: list[str] = field(default_factory=list)
    lines: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


# Regeln der einmaligen Priorisierungsentscheidung (Punkt 2/3 von #1033).
R_NOW_LISTED: Final = (
    "🟠 Hoch und unter „Als Nächstes empfohlen“ genannt → `prio:now`"
)
R_NOW_CHAIN: Final = (
    "unter „Als Nächstes empfohlen“ als Teil der #693-Kette bzw. der Messkette "
    "#689 mit #687/#688/#690 genannt → `prio:now` (Punkt 3 des Issues)"
)
R_HOCH_NEXT: Final = "🟠 Hoch, nicht unter „Als Nächstes empfohlen“ → `prio:next`"
R_MITTEL_NEXT: Final = (
    "🟡 Mittel, nächster Schritt startbereit, in Bearbeitung oder nur durch ein "
    "`prio:now`-Issue blockiert → `prio:next`"
)
R_MITTEL_LATER: Final = (
    "🟡 Mittel, nächster Schritt zurückgestellt oder mehrstufig blockiert → `prio:later`"
)
R_NIEDRIG: Final = "🟢 Niedrig → `prio:later`"
R_BETRIEB: Final = (
    "🟡 Mittel, dauerhaft offenes Betriebs-/Beobachtungs-Issue ohne Arbeitspaket → "
    "`prio:later`; kein Blocker-Label (Punkt 2 des Issues)"
)

_HW: Final = "reale EufyMake-Hardware"

#: Die 41 Tabellenzeilen mit Übernahmekommentar-Pflicht (Stand dd6c572).
LEGACY_ROWS: Final[frozenset[int]] = frozenset(
    {245, 681, 682, 687, 688, 689, 690, 691, 693, 694, 695, 696, 882}
    | set(range(883, 908))
    | {914, 918, 939}
)

#: Versionierte Entscheidungsakte über den Cutover-Bestand (52 offene Issues).
DECISIONS: Final[Mapping[int, Decision]] = {
    # EufyMake-Epic #681
    681: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(688, 689, 690)),
    687: Decision(
        PRIO_NOW, R_NOW_CHAIN, blocked_by=(688, 689, 690),
        extern=f"{_HW} (physische Drucke und Messungen)",
    ),
    688: Decision(
        PRIO_NOW, R_NOW_CHAIN,
        extern=f"{_HW} (physischer Drucker, Fixtures, Messprotokoll)",
    ),
    689: Decision(
        PRIO_NOW, R_NOW_LISTED,
        extern=f"{_HW} (physische Registrierung, Messungen, Drucktoleranzen)",
    ),
    690: Decision(
        PRIO_NOW, R_NOW_CHAIN, extern=f"{_HW} (physische Drucke, Materialverbrauch)",
    ),
    691: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(688, 689, 690)),
    # COLOR-Epic #682
    682: Decision(PRIO_NEXT, R_MITTEL_NEXT),
    693: Decision(PRIO_NOW, R_NOW_CHAIN),
    694: Decision(PRIO_NEXT, R_MITTEL_NEXT, blocked_by=(693,)),
    695: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(693, 694)),
    696: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(695,)),
    # Mac-App-Store-Epic #882
    882: Decision(PRIO_NEXT, R_MITTEL_NEXT, blocked_by=(883,)),
    883: Decision(PRIO_NOW, R_NOW_LISTED),
    884: Decision(
        PRIO_NEXT, R_HOCH_NEXT,
        extern="Apple Developer Program – Kontotyp, Enrollment/2FA, Renewal (Account Holder)",
    ),
    885: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(884,)),
    886: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(883,)),
    887: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(886,)),
    888: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(886,)),
    889: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(886,)),
    890: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(886,)),
    891: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(883,)),
    892: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(891,)),
    893: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(883,)),
    894: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(883,)),
    895: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(885, 886, 894)),
    896: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(895,)),
    897: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(885, 895, 896)),
    898: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(895, 897)),
    899: Decision(
        PRIO_NEXT, R_HOCH_NEXT, blocked_by=(898,),
        extern="self-hosted macOS-ARM64-Hardware für die sandboxed Abnahme-Smokes",
    ),
    900: Decision(
        PRIO_NEXT, R_HOCH_NEXT, blocked_by=(897, 901),
        extern="Account Holder und Tester (TestFlight, Fremdgerät)",
    ),
    901: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(884, 885)),
    902: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(895,)),
    903: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(891, 893)),
    904: Decision(
        PRIO_NEXT, R_HOCH_NEXT, blocked_by=(884,),
        extern="Owner-Selbsteinschätzung und Rechtsprüfung (Trader-Status, DDG/GPSR)",
    ),
    905: Decision(PRIO_NEXT, R_HOCH_NEXT, blocked_by=(898, 899)),
    906: Decision(
        PRIO_NEXT, R_HOCH_NEXT, blocked_by=(896, 897, 899, 901, 902, 903, 904, 905),
        extern="Apple-Review und Release-Owner (Ersteinreichung)",
    ),
    907: Decision(PRIO_LATER, R_MITTEL_LATER, blocked_by=(906,)),
    # Release-Prozess-Epic #914
    914: Decision(PRIO_NOW, R_NOW_LISTED, blocked_by=(918,)),
    918: Decision(
        PRIO_NOW, R_NOW_LISTED,
        extern="der nächste echte Release-Lauf (Post-Release-Abnahme auf `release/vX.Y.Z`)",
    ),
    # Betrieb / operativ
    939: Decision(PRIO_LATER, R_BETRIEB),
    245: Decision(PRIO_LATER, R_NIEDRIG, extern="OpenAI-Billing/Quota (Repo-Owner)"),
    # Prozess-Entschlackungs-Epic #1032 (kein Legacy-Kommentar, nur Label/Abhängigkeit)
    1032: Decision(PRIO_NOW, R_NOW_LISTED),
    1033: Decision(PRIO_NOW, R_NOW_LISTED),
    1034: Decision(PRIO_NEXT, R_MITTEL_NEXT),
    1035: Decision(PRIO_NEXT, R_MITTEL_NEXT),
    1037: Decision(PRIO_NOW, R_NOW_LISTED),
    1038: Decision(PRIO_LATER, R_NIEDRIG),
    1039: Decision(PRIO_LATER, R_MITTEL_LATER),
    1040: Decision(PRIO_NOW, R_NOW_LISTED, blocked_by=(1033,)),
    1041: Decision(
        PRIO_NEXT, R_MITTEL_NEXT, blocked_by=(1040, 1037),
        note="#1036 ist in der Tabelle als Voraussetzung genannt, aber bereits geschlossen – "
        "keine Abhängigkeit gesetzt",
    ),
    1042: Decision(PRIO_NEXT, R_MITTEL_NEXT, blocked_by=(1040,)),
    1043: Decision(
        PRIO_LATER, R_MITTEL_LATER, blocked_by=(1040, 1035, 1037, 1041),
        note="#1036 ist in der Tabelle als Voraussetzung genannt, aber bereits geschlossen – "
        "keine Abhängigkeit gesetzt",
    ),
}


# --- Tabelle -----------------------------------------------------------------


def parse_triage_table(text: str) -> dict[int, TriageRow]:
    """Liest die Triage-Tabelle aus ``RECOMMENDATIONS.md`` (deutsche Fassung).

    Erwartet sechs Zellen je Zeile; die fünfte („Empfohlenes Modell“) wird
    verworfen. Zellen enthalten keinen Pipe – eine abweichende Zellenzahl ist
    ein Fehler, keine stille Auslassung.
    """
    section = TRIAGE_SECTION_RE.search(text)
    if section is None:
        raise CutoverError("Abschnitt „Offene GitHub-Issues“ nicht gefunden")
    rows: dict[int, TriageRow] = {}
    for line in section.group(0).splitlines():
        if not line.startswith("| [#"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != 6:
            raise CutoverError(f"Tabellenzeile mit {len(cells)} statt 6 Zellen: {line[:60]}…")
        link = ISSUE_LINK_RE.match(cells[0])
        if link is None or link.group(1) != link.group(2):
            raise CutoverError(f"Ungültige Issue-Zelle: {cells[0]}")
        number = int(link.group(1))
        if number in rows:
            raise CutoverError(f"#{number} steht doppelt in der Tabelle")
        rows[number] = TriageRow(
            number=number, title=cells[1], relevance=cells[2],
            complexity=cells[3], next_step=cells[5],
        )
    if not rows:
        raise CutoverError("Triage-Tabelle ist leer")
    return rows


def parse_next_steps(text: str) -> list[str]:
    """Liest die nummerierten Punkte unter „Als Nächstes empfohlen“ wortgleich."""
    match = NEXT_STEPS_RE.search(text)
    if match is None:
        raise CutoverError("Abschnitt „Als Nächstes empfohlen“ nicht gefunden")
    items: list[str] = []
    for raw in match.group(1).splitlines():
        if not raw.strip():
            continue
        item = NEXT_ITEM_RE.match(raw)
        if item is not None:
            items.append(item.group(2).strip())
        elif items and raw.startswith(" "):
            items[-1] = f"{items[-1]} {raw.strip()}"
        else:
            raise CutoverError(f"Unerwartete Zeile unter „Als Nächstes empfohlen“: {raw!r}")
    if not items:
        raise CutoverError("„Als Nächstes empfohlen“ ist leer")
    return items


# --- Entscheidungsakte -------------------------------------------------------


def validate_decisions(
    decisions: Mapping[int, Decision], rows: Mapping[int, TriageRow],
) -> None:
    """Innere Konsistenz der Akte gegen die Tabelle (netzfrei)."""
    # Nur die Zeilen, deren Text übernommen wird, müssen in der Tabelle stehen und
    # entschieden sein. Die Tabelle selbst ist bewusst *kein* Prüfgegenstand: Sie
    # wächst mit jedem neuen Issue weiter (bis #1040), und die Voll-Abdeckung des
    # offenen Bestands bindet ``validate_live_coverage`` an den Live-Stand.
    missing_rows = sorted(LEGACY_ROWS - rows.keys())
    if missing_rows:
        raise CutoverError(f"Legacy-Zeilen fehlen in der Tabelle: {missing_rows}")
    undecided = sorted(LEGACY_ROWS - decisions.keys())
    if undecided:
        raise CutoverError(f"Legacy-Zeilen ohne Entscheidung: {undecided}")
    for number, decision in decisions.items():
        if decision.prio not in PRIO_LABELS:
            raise CutoverError(f"#{number}: unbekanntes Prio-Label {decision.prio!r}")
        if decision.extern is not None and not decision.extern.strip():
            raise CutoverError(f"#{number}: externer Blocker ohne Begründung")
        if number in decision.blocked_by:
            raise CutoverError(f"#{number} blockiert sich selbst")
        unknown = sorted(set(decision.blocked_by) - decisions.keys())
        if unknown:
            raise CutoverError(f"#{number}: Blocker ohne Entscheidung (geschlossen?): {unknown}")
        if len(set(decision.blocked_by)) != len(decision.blocked_by):
            raise CutoverError(f"#{number}: doppelter Blocker")


def validate_live_coverage(
    decisions: Mapping[int, Decision], live: Mapping[int, LiveIssue],
) -> None:
    """Die Akte muss exakt den offenen Live-Bestand abdecken – nicht mehr, nicht weniger."""
    extra = sorted(live.keys() - decisions.keys())
    stale = sorted(decisions.keys() - live.keys())
    if extra or stale:
        raise CutoverError(
            f"Akte ≠ Live-Bestand: ohne Entscheidung {extra}, nicht mehr offen {stale}"
        )


# --- Kommentare --------------------------------------------------------------


def render_comment(row: TriageRow, decision: Decision) -> str:
    """Übernahmekommentar nach dem Muster aus #1033 (ohne Modellspalte)."""
    lines: list[str] = []
    if decision.extern is not None:
        lines.append(f"{EXTERN_PREFIX}{decision.extern}")
        lines.append("")
    lines.append(
        f"{COMMENT_MARKER} (Stand {TABLE_DATE}, Commit {TABLE_COMMIT}):** "
        f"Relevanz {row.relevance}; Komplexität {row.complexity}; "
        f"nächster Schritt: {row.next_step}"
    )
    lines.append("")
    lines.append(
        f"Einmalige Priorisierungsentscheidung (Owner-Regel aus #1033): {decision.rule}."
    )
    if decision.blocked_by:
        deps = ", ".join(f"#{n}" for n in decision.blocked_by)
        lines.append(f"Interne Blocker als native Abhängigkeit „blocked by“: {deps}.")
    if decision.note is not None:
        lines.append(f"Bewusste Abweichung vom Tabellentext: {decision.note}.")
    return "\n".join(lines) + FOOTER


def render_extern_note(decision: Decision) -> str:
    """Begründungszeile für ``blocked:extern`` ohne Legacy-Übernahme."""
    if decision.extern is None:
        raise CutoverError("render_extern_note ohne externen Blocker")
    return f"{EXTERN_PREFIX}{decision.extern}" + FOOTER


def render_epic_comment(next_steps: Iterable[str], cutover_commit: str) -> str:
    """Hält die Punkte unter „Als Nächstes empfohlen“ wortgleich im Epic fest."""
    body = [
        f"{EPIC_MARKER} (Cutover-Stand {cutover_commit}):** Die nummerierten Punkte "
        "wortgleich aus der Datei am Cutover-Commit; die drei aus #1033 (#693-Kette, "
        "#883, #689 mit #687/#688/#690) tragen `prio:now`.",
        "",
    ]
    body.extend(f"{index}. {item}" for index, item in enumerate(next_steps, start=1))
    return "\n".join(body) + FOOTER


# --- GitHub-Client -----------------------------------------------------------


Opener = Callable[..., Any]


class GitHubClient:
    """Dünner urllib-Client; ``opener`` ist der Einhängepunkt der Tests."""

    def __init__(
        self, repo: str, token: str | None, opener: Opener = urllib.request.urlopen,
    ) -> None:
        self.repo = repo
        self._token = token
        self._opener = opener

    def _request(self, method: str, path: str, payload: Any | None = None) -> Any:
        url = path if path.startswith("http") else f"{API_ROOT}{path}"
        data = None if payload is None else json.dumps(payload).encode("utf-8")
        headers = {
            "Accept": "application/vnd.github+json",
            "User-Agent": USER_AGENT,
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if self._token:
            headers["Authorization"] = f"Bearer {self._token}"
        if data is not None:
            headers["Content-Type"] = "application/json"
        request = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with self._opener(request, timeout=REQUEST_TIMEOUT_S) as response:
                raw = response.read()
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")[:300]
            raise CutoverError(f"{method} {path} → HTTP {exc.code}: {detail}") from exc
        except (urllib.error.URLError, OSError) as exc:
            raise CutoverError(f"{method} {path} → {exc}") from exc
        if not raw:
            return None
        return json.loads(raw.decode("utf-8"))

    def _paginate(self, path: str) -> list[Any]:
        items: list[Any] = []
        page = 1
        while True:
            sep = "&" if "?" in path else "?"
            chunk = self._request("GET", f"{path}{sep}per_page=100&page={page}")
            if not isinstance(chunk, list):
                raise CutoverError(f"GET {path}: Liste erwartet")
            items.extend(chunk)
            if len(chunk) < 100:
                return items
            page += 1

    # -- Lesen
    def list_open_issues(self) -> dict[int, LiveIssue]:
        live: dict[int, LiveIssue] = {}
        for item in self._paginate(f"/repos/{self.repo}/issues?state=open"):
            if "pull_request" in item:
                continue
            number = int(item["number"])
            live[number] = LiveIssue(
                number=number, issue_id=int(item["id"]),
                labels=frozenset(str(label["name"]) for label in item["labels"]),
            )
        return live

    def list_labels(self) -> set[str]:
        return {str(label["name"]) for label in self._paginate(f"/repos/{self.repo}/labels")}

    def list_comment_bodies(self, number: int) -> list[str]:
        return [
            str(comment["body"])
            for comment in self._paginate(f"/repos/{self.repo}/issues/{number}/comments")
        ]

    def list_blocked_by(self, number: int) -> set[int]:
        """Offene native Blocker; ein geschlossener Blocker blockiert nicht mehr."""
        return {
            int(item["number"])
            for item in self._paginate(
                f"/repos/{self.repo}/issues/{number}/dependencies/blocked_by"
            )
            if item.get("state", "open") == "open"
        }

    # -- Schreiben
    def create_label(self, name: str, color: str, description: str) -> None:
        self._request(
            "POST", f"/repos/{self.repo}/labels",
            {"name": name, "color": color, "description": description},
        )

    def add_labels(self, number: int, labels: list[str]) -> None:
        self._request("POST", f"/repos/{self.repo}/issues/{number}/labels", {"labels": labels})

    def remove_label(self, number: int, label: str) -> None:
        quoted = urllib.parse.quote(label, safe="")
        self._request("DELETE", f"/repos/{self.repo}/issues/{number}/labels/{quoted}")

    def add_blocked_by(self, number: int, blocker_id: int) -> None:
        self._request(
            "POST", f"/repos/{self.repo}/issues/{number}/dependencies/blocked_by",
            {"issue_id": blocker_id},
        )

    def create_comment(self, number: int, body: str) -> None:
        self._request("POST", f"/repos/{self.repo}/issues/{number}/comments", {"body": body})


# --- Plan / Apply ------------------------------------------------------------


def _marker_state(bodies: Iterable[str], marker: str, expected: str) -> tuple[int, int]:
    """(Kommentare mit Marker, davon byteweise gleich der erwarteten Fassung)."""
    marked = [body for body in bodies if marker in body]
    return len(marked), sum(1 for body in marked if body == expected)


def _needs_comment(number: int, bodies: Iterable[str], marker: str, expected: str) -> bool:
    """Fehlt der Kommentar → True; vorhanden und wortgleich → False; sonst Abbruch.

    Ein abweichender oder doppelter Kommentar wird nie still übersprungen: Ein
    verkürzter Altbestand mit passendem Marker ließe sonst „übertragen“ melden,
    wo der Text gar nicht wortgleich ist – das behebt ein Mensch, nicht das Skript.
    """
    marked, exact = _marker_state(bodies, marker, expected)
    if marked == 0:
        return True
    if marked == 1 and exact == 1:
        return False
    raise CutoverError(
        f"#{number}: {marked} Kommentar(e) mit Marker {marker[:40]!r}, "
        f"{exact} davon wortgleich – von Hand bereinigen"
    )


def build_plan(
    client: GitHubClient,
    rows: Mapping[int, TriageRow],
    decisions: Mapping[int, Decision],
    next_steps: list[str],
    cutover_commit: str,
) -> list[Action]:
    """Ermittelt die noch fehlenden Schritte gegen den Live-Stand (idempotent)."""
    live = client.list_open_issues()
    validate_live_coverage(decisions, live)
    actions: list[Action] = []
    existing = client.list_labels()
    for name, color, description in LABEL_SPECS:
        if name not in existing:
            actions.append(Action("create_label", 0, json.dumps([name, color, description])))
    for number in sorted(decisions):
        decision = decisions[number]
        issue = live[number]
        wanted = {decision.prio} | ({BLOCKED_EXTERN} if decision.extern else set())
        unwanted = (set(PRIO_LABELS) | {BLOCKED_EXTERN}) - wanted
        for label in sorted(wanted - issue.labels):
            actions.append(Action("add_label", number, label))
        for label in sorted(unwanted & issue.labels):
            actions.append(Action("remove_label", number, label))
        present = client.list_blocked_by(number)
        unexpected = sorted(present - set(decision.blocked_by))
        if unexpected:
            # Ein von Hand gesetzter Blocker außerhalb der Akte wird nicht still
            # entfernt und nicht still geduldet: Akte oder Issue muss jemand angleichen.
            raise CutoverError(f"#{number}: native Blocker außerhalb der Akte: {unexpected}")
        for blocker in decision.blocked_by:
            if blocker not in present:
                actions.append(Action("add_blocked_by", number, str(blocker)))
        if number in LEGACY_ROWS:
            expected = render_comment(rows[number], decision)
            if _needs_comment(number, client.list_comment_bodies(number), COMMENT_MARKER, expected):
                actions.append(Action("comment", number, expected))
        elif decision.extern is not None:
            expected = render_extern_note(decision)
            if _needs_comment(number, client.list_comment_bodies(number), EXTERN_PREFIX, expected):
                actions.append(Action("comment", number, expected))
    expected_epic = render_epic_comment(next_steps, cutover_commit)
    if _needs_comment(
        EPIC_ISSUE, client.list_comment_bodies(EPIC_ISSUE), EPIC_MARKER, expected_epic
    ):
        actions.append(Action("comment", EPIC_ISSUE, expected_epic))
    return actions


def describe(action: Action) -> str:
    if action.kind == "create_label":
        name, _color, _description = json.loads(action.payload)
        return f"Label anlegen: {name}"
    if action.kind == "comment":
        first = action.payload.splitlines()[0]
        return f"#{action.issue}: Kommentar „{first[:70]}…“"
    if action.kind == "add_blocked_by":
        return f"#{action.issue}: blocked by #{action.payload}"
    return f"#{action.issue}: {action.kind} {action.payload}"


def apply_plan(
    client: GitHubClient, actions: list[Action], live: Mapping[int, LiveIssue],
) -> None:
    for action in actions:
        if action.kind == "create_label":
            name, color, description = json.loads(action.payload)
            client.create_label(name, color, description)
        elif action.kind == "add_label":
            client.add_labels(action.issue, [action.payload])
        elif action.kind == "remove_label":
            client.remove_label(action.issue, action.payload)
        elif action.kind == "add_blocked_by":
            blocker = live.get(int(action.payload))
            if blocker is None:
                raise CutoverError(
                    f"#{action.issue}: Blocker #{action.payload} ist nicht mehr offen"
                )
            client.add_blocked_by(action.issue, blocker.issue_id)
        elif action.kind == "comment":
            client.create_comment(action.issue, action.payload)
        else:  # pragma: no cover - Programmierfehler
            raise CutoverError(f"Unbekannte Aktion {action.kind}")


# --- Verify ------------------------------------------------------------------


def verify(
    client: GitHubClient,
    rows: Mapping[int, TriageRow],
    decisions: Mapping[int, Decision],
    next_steps: list[str],
    cutover_commit: str,
    now: datetime | None = None,
) -> VerifyReport:
    """Die zwei Cutover-Abgleiche aus #1033 plus Blocker-Konsistenz; schreibt nichts.

    Übernahme- und Epic-Kommentar gelten nur **wortgleich** zur gerenderten
    Fassung als übertragen – ein Marker allein reicht nicht.
    """
    checked_at = (now or datetime.now(timezone.utc)).strftime("%Y-%m-%dT%H:%M:%SZ")
    live = client.list_open_issues()
    report = VerifyReport(
        checked_at=checked_at,
        query=f"GET /repos/{client.repo}/issues?state=open (Pull Requests ausgeschlossen)",
        open_count=len(live),
    )
    # (a) Legacy-Tabellenzeilen ↔ genau ein wortgleicher Übernahmekommentar
    missing: list[int] = []
    duplicated: list[int] = []
    divergent: list[int] = []
    legacy_open = sorted(n for n in LEGACY_ROWS if n in live)
    for number in legacy_open:
        decision = decisions.get(number)
        row = rows.get(number)
        if decision is None or row is None:
            missing.append(number)
            continue
        marked, exact = _marker_state(
            client.list_comment_bodies(number), COMMENT_MARKER, render_comment(row, decision)
        )
        if marked == 0:
            missing.append(number)
        elif marked > 1:
            duplicated.append(number)
        elif exact != 1:
            divergent.append(number)
    conforming = len(legacy_open) - len(missing) - len(duplicated) - len(divergent)
    report.lines.append(
        f"(a) Tabellenzeilen ↔ Übernahmekommentare: {conforming}/{len(legacy_open)} "
        "offene Legacy-Zeilen mit genau einem wortgleichen Kommentar"
    )
    if missing:
        report.problems.append(f"(a) ohne Übernahmekommentar: {missing}")
    if duplicated:
        report.problems.append(f"(a) mehrfacher Übernahmekommentar: {duplicated}")
    if divergent:
        report.problems.append(f"(a) Übernahmekommentar nicht wortgleich: {divergent}")
    if EPIC_ISSUE in live:
        marked, exact = _marker_state(
            client.list_comment_bodies(EPIC_ISSUE), EPIC_MARKER,
            render_epic_comment(next_steps, cutover_commit),
        )
        if (marked, exact) != (1, 1):
            report.problems.append(
                f"Epic #{EPIC_ISSUE}: {marked} Kommentar(e) „Als Nächstes empfohlen“, "
                f"{exact} wortgleich"
            )
    # (b) Live-Bestand ↔ genau ein prio:*-Label
    bad_prio: list[int] = []
    for number, issue in sorted(live.items()):
        if len(issue.labels & set(PRIO_LABELS)) != 1:
            bad_prio.append(number)
    report.lines.append(
        f"(b) offener Live-Bestand ↔ genau ein `prio:*`-Label: "
        f"{len(live) - len(bad_prio)}/{len(live)} Issues"
    )
    if bad_prio:
        report.problems.append(f"(b) nicht genau ein prio-Label: {bad_prio}")
    # Blocker-Konsistenz gegen die Akte: Label, Begründungszeile, native Abhängigkeiten
    extern_mismatch: list[int] = []
    extern_unexplained: list[int] = []
    dep_missing: list[str] = []
    dep_unexpected: list[str] = []
    dep_expected = 0
    for number, issue in sorted(live.items()):
        decision = decisions.get(number)
        if decision is None:
            report.problems.append(f"#{number} offen, aber ohne Entscheidung in der Akte")
            continue
        if (BLOCKED_EXTERN in issue.labels) != (decision.extern is not None):
            extern_mismatch.append(number)
        if decision.extern is not None:
            first_lines = {
                body.splitlines()[0] for body in client.list_comment_bodies(number) if body
            }
            if f"{EXTERN_PREFIX}{decision.extern}" not in first_lines:
                extern_unexplained.append(number)
        present = client.list_blocked_by(number)
        # Ein inzwischen geschlossener Blocker ist erfüllt, nicht fehlend – GitHub
        # führt ihn nicht mehr als offene Abhängigkeit, die Akte bleibt Snapshot.
        expected = [b for b in decision.blocked_by if b in live]
        dep_expected += len(expected)
        dep_missing.extend(f"#{number}←#{b}" for b in expected if b not in present)
        dep_unexpected.extend(
            f"#{number}←#{b}" for b in sorted(present - set(decision.blocked_by))
        )
    extern_count = sum(1 for issue in live.values() if BLOCKED_EXTERN in issue.labels)
    dep_count = dep_expected
    report.lines.append(
        f"Blocker: {extern_count} × `{BLOCKED_EXTERN}` (je mit Begründungszeile), "
        f"{dep_count - len(dep_missing)}/{dep_count} native Abhängigkeiten aus der Akte "
        f"vorhanden, {len(dep_unexpected)} außerhalb der Akte"
    )
    if extern_mismatch:
        report.problems.append(f"blocked:extern ≠ Akte: {extern_mismatch}")
    if extern_unexplained:
        report.problems.append(f"blocked:extern ohne Begründungszeile: {extern_unexplained}")
    if dep_missing:
        report.problems.append(f"fehlende Abhängigkeiten: {dep_missing}")
    if dep_unexpected:
        report.problems.append(f"native Blocker außerhalb der Akte: {dep_unexpected}")
    return report


def render_report(report: VerifyReport, cutover_commit: str) -> str:
    verdict = "grün" if report.ok else "ROT"
    out = [
        f"**Cutover-Abgleich {verdict}** – {report.checked_at}, Abfrage `{report.query}`, "
        f"{report.open_count} offene Issues; übertragene Tabelle: Stand {TABLE_DATE} "
        f"(Commit {TABLE_COMMIT}), Cutover-Stand {cutover_commit}.",
        "",
    ]
    out.extend(f"- {line}" for line in report.lines)
    if report.problems:
        out.append("")
        out.extend(f"- ❌ {problem}" for problem in report.problems)
    return "\n".join(out)


def render_decision_table(
    rows: Mapping[int, TriageRow], decisions: Mapping[int, Decision],
) -> str:
    out = ["| # | Prio | Interne Blocker | Extern | Kommentar |", "|---|---|---|---|---|"]
    for number in sorted(decisions):
        d = decisions[number]
        deps = ", ".join(f"#{n}" for n in d.blocked_by) or "–"
        extern = "ja" if d.extern else "–"
        legacy = "Übernahme" if number in LEGACY_ROWS else "–"
        out.append(f"| #{number} | `{d.prio}` | {deps} | {extern} | {legacy} |")
    return "\n".join(out)


# --- CLI ---------------------------------------------------------------------


_SHA_RE: Final = re.compile(r"^[0-9a-f]{7,40}$")


def resolve_commit(
    ref: str, repo_root: Path, run: Callable[..., Any] = subprocess.run,
) -> str:
    """Löst eine Git-Referenz auf einen unveränderlichen Kurz-SHA auf.

    Der Cutover-Stand wandert wörtlich in Epic-Kommentar und Bericht; ein
    ``HEAD`` dort bezeichnete nach dem nächsten Commit einen anderen Stand.
    """
    if _SHA_RE.match(ref):
        return ref
    try:
        result = run(
            ["git", "-C", str(repo_root), "rev-parse", "--short=7", "--verify", f"{ref}^{{commit}}"],
            capture_output=True, text=True, check=False,
        )
    except OSError as exc:
        raise CutoverError(f"git nicht aufrufbar: {exc}") from exc
    sha = str(result.stdout).strip()
    if result.returncode != 0 or not _SHA_RE.match(sha):
        raise CutoverError(f"Cutover-Commit {ref!r} nicht auflösbar: {str(result.stderr).strip()}")
    return sha


def _load_table(path: Path) -> tuple[dict[int, TriageRow], list[str]]:
    text = path.read_text(encoding="utf-8")
    rows = parse_triage_table(text)
    validate_decisions(DECISIONS, rows)
    return rows, parse_next_steps(text)


def _client(args: argparse.Namespace) -> GitHubClient:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or None
    if token is None:
        print("[cutover] Hinweis: kein GH_TOKEN/GITHUB_TOKEN – Anfragen laufen anonym.")
    return GitHubClient(str(args.repo), token)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--repo", default=REPO)
    parser.add_argument(
        "--recommendations", type=Path,
        default=Path(__file__).resolve().parent.parent / "RECOMMENDATIONS.md",
    )
    parser.add_argument(
        "--cutover-commit", default="HEAD",
        help="SHA des Stands, dessen Tabelle übertragen wird (für die Kommentare)",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("plan", help="Akte gegen die Tabelle prüfen und als Tabelle ausgeben")
    apply_parser = sub.add_parser("apply", help="fehlende Labels/Abhängigkeiten/Kommentare setzen")
    apply_parser.add_argument("--dry-run", action="store_true")
    sub.add_parser("verify", help="die zwei Cutover-Abgleiche ausführen (schreibt nichts)")
    args = parser.parse_args(argv)

    try:
        rows, next_steps = _load_table(args.recommendations)
        cutover_commit = resolve_commit(str(args.cutover_commit), args.recommendations.parent)
        if args.command == "plan":
            print(render_decision_table(rows, DECISIONS))
            print(f"\n{len(rows)} Tabellenzeilen, {len(LEGACY_ROWS)} Legacy-Zeilen, "
                  f"{len(DECISIONS)} Entscheidungen, {len(next_steps)} Als-Nächstes-Punkte, "
                  f"Cutover-Stand {cutover_commit}")
            return 0
        client = _client(args)
        if args.command == "apply":
            actions = build_plan(client, rows, DECISIONS, next_steps, cutover_commit)
            for action in actions:
                print(f"[cutover] {'plan' if args.dry_run else 'do'}: {describe(action)}")
            print(f"[cutover] {len(actions)} Aktionen")
            if not args.dry_run and actions:
                apply_plan(client, actions, client.list_open_issues())
            return 0
        report = verify(client, rows, DECISIONS, next_steps, cutover_commit)
        print(render_report(report, cutover_commit))
        return 0 if report.ok else 1
    except CutoverError as exc:
        print(f"[cutover] Fehler: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
